# Generated by Django 3.1.1 on 2020-10-06 09:00
# Has manual edits

from django.conf import settings
from django.db import migrations, models, transaction
import django.db.models.deletion
import django.utils.timezone


def addSentryRows(apps, schema_editor):
    Restaurant = apps.get_model("voting", "Restaurant")
    RestaurantChoiceHistory = apps.get_model("voting", "RestaurantChoiceHistory")
    with transaction.atomic():
        restaurant = Restaurant.objects.create(creator=None, deletedAt=None, name="Skip lunch")
        RestaurantChoiceHistory.objects.create(createdAt="2000-01-01", restaurant=restaurant)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletedAt', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantChoiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.restaurant')),
                ('restaurantChoiceHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.restaurantchoicehistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(addSentryRows),
    ]
